# Generated by Django 3.0.5 on 2023-11-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0002_auto_20231107_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PR', 'Premium'), ('LX', 'Luxury'), ('OW', 'Comfort'), ('EC', 'Economy'), ('BS', 'Basic')], default='Ngong', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='Mboa Technologies'),
        ),
    ]
