# Generated by Django 3.0.5 on 2023-11-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='market_cap',
            field=models.CharField(max_length=200),
        ),
    ]
