# Generated by Django 3.0.5 on 2024-01-13 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20231104_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
