# Generated by Django 5.0.4 on 2024-06-05 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('P2P', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='Recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SendMoney', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendmoney',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
