# Generated by Django 3.0.5 on 2023-11-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FX_Profile', '0003_auto_20231031_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image03',
        ),
    ]
