# Generated by Django 3.0.5 on 2023-11-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231110_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='MboaCoins_Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
