# Generated by Django 3.0.5 on 2023-11-13 08:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userbankaccount_mboacoins_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='useraddress',
            name='Name',
            field=models.CharField(default='Mboa Technologies', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='apartment_address',
            field=models.CharField(default='Ngong Rd', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='c_image',
            field=models.ImageField(default='img/Mboa Academy.jpg', upload_to='products_img'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='p_image',
            field=models.ImageField(default='img/Mboa Academy.jpg', upload_to='products_img'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='slug',
            field=models.SlugField(default='1'),
        ),
    ]
