# Generated by Django 3.0.5 on 2024-04-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0002_auto_20240412_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'BquWNUxC6yC8PgtN8zVzPTQDzpzs8n3E7cUFcNZ4U//D5AgUfrrqHOVNNQfU5doYrot2P5NrjTYijfiWqemLVg==', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='0b2ef356b608116fdd9987573cb16f43ec706148b1038a5fd1f1b035903548f2', max_length=20, null=True),
        ),
    ]
