# Generated by Django 3.0.5 on 2024-04-12 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('openSoko', '0003_auto_20240412_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'FxjB2YXDkf8KOg0mvhL3NomIhwgdnXt0KKd7WRGA9eE/nPzzM4VllhAVRyM2XI/VxRUCRLh7bT+YKRQ/qiyepg==', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='bb18ba766ceb47e64eaac5ebd8ae349d3d6e3ebec7c50586c8d34852b2a3be0a', max_length=20, null=True),
        ),
    ]
