# Generated by Django 3.0.5 on 2024-04-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openSoko', '0007_auto_20240413_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, default=b'XWjrMfPfBP5U22EPtTF9AKdnBZ5bt/sXfwOgt3mSml+rx0WAm+TcBq5LhKfsI2K4M6/N5r2zMPHhwQGtIFg+FQ==', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code_confirm',
            field=models.CharField(blank=True, default='1548e2af1e316ba5d4db3fea62064566bae267b21a0d12530bd25a76c6b48005', max_length=20, null=True),
        ),
    ]
